# Site settings
title: Resat Amin
email: resat.amin@gmail.com
author: Resat Amin

keywords: resat amin, sociology, technology and society, feminist research, digital media, Bangladesh, FAU
description: Resat Amin - Sociology graduate student researching the intersection of society and emerging technologies, focusing on digital platforms, power dynamics, and social inequalities.

# Only use this if you are serving your site via Github Pages
github:
#  url: "https://resatamin.netlify.app"

header: images/profile.jpg

# Formspree contact Form (uncomment and add your form URL)
#contact_form: "https://formspree.io/YOUR_FORM_ID"


# Exclude build artifacts and dependencies
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, resat-personal-site-theme-*.gem, .DS_Store, .idea, README.md]



# Build settings
markdown: kramdown
kramdown:
  input: GFM

# This is a personal website, not a theme
  
# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

# collections:
  # - galleries (removed - not used)

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                                #enter your App ID
facebook_locale: en_US
facebook_page:                                  #the URL of your Facebook Page
facebook_image: images/author.jpg                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: AminResat
twitter_card: true
twitter_image: images/author.jpg                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
